version: '3'

services:
  db:
    image: postgres:latest
    container_name: bd_proj_db
    ports:
      - '5432:5432'
    volumes:
#      - './docker_data/db/:/var/lib/postgresql/data/'
      - './db/sql/:/docker-entrypoint-initdb.d/'
      - './db/csv/:/csv/'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}